### ISSUE TITLE
@toreda/chk: Not found

### ISSUE THREAD

**Issue by umer-surkhail** [toreda/chk#1]
I am trying to install but its giving me 404
I tried both with Yarn as well as NPM but it throwing me error of 404

<img width="1281" alt="Screenshot 2022-05-16 at 7 12 12 PM" src="https://user-images.githubusercontent.com/56860234/168612504-1362aa76-4166-4141-bfdf-895f7d878f67.png">

**Comment by mbrich** [comment]
Thank you for posting about this issue. We pushed a new version which fixes the problem.
